dist: xenial
sudo: required
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libsdl2-dev
    - g++-8
before_install:
  - chmod +x setup.sh
  - ./setup.sh
  - mkdir Build && cd Build
  - cmake -DCMAKE_BUILD_TYPE=Release ..

# Enable C++ support
language: cpp

# Compiler selection
compiler:
  - gcc-8

# Build steps
script:
  - make
