dist: trusty
sudo: required
addons:
  apt:
    packages:
    - libsdl2-dev
before_install:
  - chmod +x setup.sh
  - ./setup.sh

# Enable C++ support
language: cpp

# Compiler selection
compiler:
  - gcc

# Build steps
script:
  - make CONFIG=RELEASE
