dist: trusty
sudo: required
addons:
  apt:
    packages:
    - libsdl2-dev
before_install:
  - chmod +x setup.sh
  - ./setup.sh
  - mkdir Build && cd Build
  - cmake -DCMAKE_BUILD_TYPE=Release ..

# Enable C++ support
language: cpp

# Compiler selection
compiler:
  - gcc

# Build steps
script:
  - make
